#include "device_window.h"
#include "device_controller.h"
#include "utf8_compat.h"

#include <QComboBox>
#include <QFormLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QLabel>
#include <QPushButton>
#include <QSerialPortInfo>
#include <QVBoxLayout>

namespace crawling {
DeviceWindow::DeviceWindow(DeviceController* controller, QWidget* parent) : QDialog(parent), controller_(controller) {
  setWindowTitle(CRAWLING_TEXT("IMU \xE4\xB8\x8E""\xE7\xBA\xBF""\xE6\xBF\x80""\xE5\x85\x89""\xE8\xAE\xBE""\xE5\xA4\x87""\xE8\xBF\x9E""\xE6\x8E\xA5""")); setMinimumWidth(680); resize(760, 520);
  auto* root = new QVBoxLayout(this);
  auto* imu = new QGroupBox(CRAWLING_TEXT("RIM302 IMU\xEF\xBC\x88""\xE7\x8B\xAC""\xE7\xAB\x8B"" RS485/RS422 \xE4\xB8\xB2""\xE5\x8F\xA3""\xEF\xBC\x89"""), this); auto* imuf = new QFormLayout(imu);
  imuPort_ = new QComboBox(imu); imuBaud_ = new QComboBox(imu); for (const int baud : {9600, 19200, 38400, 57600, 115200, 256000}) imuBaud_->addItem(QString::number(baud), baud); imuBaud_->setCurrentIndex(imuBaud_->findData(115200)); imuDivider_ = new QComboBox(imu); for (const auto n : {1,2,4,8,10,20,40,200}) imuDivider_->addItem(CRAWLING_TEXT("\xE5\x88\x86""\xE9\xA2\x91"" %1").arg(n), n);
  auto* refresh = new QPushButton(CRAWLING_TEXT("\xE5\x88\xB7""\xE6\x96\xB0""\xE4\xB8\xB2""\xE5\x8F\xA3"""), imu); autoDetect_ = new QPushButton(CRAWLING_TEXT("\xE8\x87\xAA""\xE5\x8A\xA8""\xE6\xA3\x80""\xE6\xB5\x8B""\xE5\xB9\xB6""\xE8\xBF\x9E""\xE6\x8E\xA5"" IMU / \xE7\x9B\xB8""\xE6\x9C\xBA"""), imu); imuConnect_ = new QPushButton(CRAWLING_TEXT("\xE8\xBF\x9E""\xE6\x8E\xA5"" IMU"), imu); imuState_ = new QLabel(CRAWLING_TEXT("\xE6\x9C\xAA""\xE8\xBF\x9E""\xE6\x8E\xA5"""), imu); imuValues_ = new QLabel(CRAWLING_TEXT("\xE7\xAD\x89""\xE5\xBE\x85"" RIM302 \xE6\x95\xB0""\xE6\x8D\xAE""\xE5\xB8\xA7"""), imu); imuValues_->setWordWrap(true);
  imuf->addRow(CRAWLING_TEXT("\xE4\xB8\xB2""\xE5\x8F\xA3"""), imuPort_); imuf->addRow(CRAWLING_TEXT("\xE6\xB3\xA2""\xE7\x89\xB9""\xE7\x8E\x87"""), imuBaud_); imuf->addRow(CRAWLING_TEXT("\xE8\xBE\x93""\xE5\x87\xBA""\xE5\x88\x86""\xE9\xA2\x91"""), imuDivider_); imuf->addRow(refresh); imuf->addRow(autoDetect_); imuf->addRow(imuConnect_); imuf->addRow(CRAWLING_TEXT("\xE7\x8A\xB6""\xE6\x80\x81"""), imuState_); imuf->addRow(CRAWLING_TEXT("\xE5\xA7\xBF""\xE6\x80\x81""\xE3\x80\x81""\xE9\x99\x80""\xE8\x9E\xBA""\xE4\xBB\xAA""\xE3\x80\x81""\xE5\x8A\xA0""\xE9\x80\x9F""\xE5\xBA\xA6"""), imuValues_); root->addWidget(imu);
  auto* laser = new QGroupBox(CRAWLING_TEXT("MV3DLP \xE7\xBA\xBF""\xE6\xBF\x80""\xE5\x85\x89""\xE7\x9B\xB8""\xE6\x9C\xBA""\xEF\xBC\x88""\xE4\xBB\xA5""\xE5\xA4\xAA""\xE7\xBD\x91""/USB SDK\xEF\xBC\x89"""), this); auto* lf = new QFormLayout(laser);
  cameraList_ = new QComboBox(laser); auto* scan = new QPushButton(CRAWLING_TEXT("\xE6\x89\xAB""\xE6\x8F\x8F""\xE7\x9B\xB8""\xE6\x9C\xBA"""), laser); cameraConnect_ = new QPushButton(CRAWLING_TEXT("\xE8\xBF\x9E""\xE6\x8E\xA5""\xE7\x9B\xB8""\xE6\x9C\xBA"""), laser); cameraState_ = new QLabel(CRAWLING_TEXT("\xE6\x9C\xAA""\xE8\xBF\x9E""\xE6\x8E\xA5"""), laser); cameraFrame_ = new QLabel(CRAWLING_TEXT("\xE6\x9A\x82""\xE6\x97\xA0""\xE5\xB8\xA7""\xE6\x95\xB0""\xE6\x8D\xAE"""), laser);
  lf->addRow(CRAWLING_TEXT("\xE5\xB7\xB2""\xE5\x8F\x91""\xE7\x8E\xB0""\xE7\x9B\xB8""\xE6\x9C\xBA"""), cameraList_); lf->addRow(scan); lf->addRow(cameraConnect_); lf->addRow(CRAWLING_TEXT("\xE7\x8A\xB6""\xE6\x80\x81"""), cameraState_); lf->addRow(CRAWLING_TEXT("\xE6\x9C\x80""\xE6\x96\xB0""\xE5\xB8\xA7"""), cameraFrame_); root->addWidget(laser, 1);
  connect(refresh, &QPushButton::clicked, this, &DeviceWindow::refreshPorts); connect(autoDetect_, &QPushButton::clicked, this, &DeviceWindow::autoDetect); connect(imuConnect_, &QPushButton::clicked, this, &DeviceWindow::connectImu); connect(scan, &QPushButton::clicked, this, &DeviceWindow::scanCamera); connect(cameraConnect_, &QPushButton::clicked, this, &DeviceWindow::connectCamera);
  connect(controller_, &DeviceController::imuSampleChanged, this, &DeviceWindow::updateImu, Qt::QueuedConnection); connect(controller_, &DeviceController::imuConnectionChanged, this, &DeviceWindow::updateImuState, Qt::QueuedConnection); connect(controller_, &DeviceController::sensorSettingsDetected, this, &DeviceWindow::applySensorDetection, Qt::QueuedConnection); connect(controller_, &DeviceController::deviceDetectionChanged, this, &DeviceWindow::updateDetectionState, Qt::QueuedConnection); connect(controller_, &DeviceController::cameraDevicesChanged, this, &DeviceWindow::updateCameraList, Qt::QueuedConnection); connect(controller_, &DeviceController::cameraConnectionChanged, this, &DeviceWindow::updateCameraState, Qt::QueuedConnection); connect(controller_, &DeviceController::cameraFrameChanged, this, &DeviceWindow::updateCameraFrame, Qt::QueuedConnection); refreshPorts();
}
void DeviceWindow::refreshPorts() { const auto selected=imuPort_->currentData().toString(); imuPort_->clear(); for(const auto& p: QSerialPortInfo::availablePorts()) imuPort_->addItem(p.portName()+CRAWLING_TEXT(" ")+p.description(),p.portName()); const int i=imuPort_->findData(selected); if(i>=0) imuPort_->setCurrentIndex(i); }
void DeviceWindow::autoDetect() { autoDetect_->setEnabled(false); QMetaObject::invokeMethod(controller_, "autoDetectDevices", Qt::QueuedConnection, Q_ARG(QString, imuPort_->currentData().toString()), Q_ARG(QString, cameraList_->currentText().section(" | ", 0, 0))); }
void DeviceWindow::connectImu() { if(imuConnect_->text().startsWith(CRAWLING_TEXT("\xE6\x96\xAD""\xE5\xBC\x80"""))) { QMetaObject::invokeMethod(controller_, "disconnectImu", Qt::QueuedConnection); } else { QMetaObject::invokeMethod(controller_, "connectImu", Qt::QueuedConnection, Q_ARG(QString, imuPort_->currentData().toString()), Q_ARG(int, imuBaud_->currentData().toInt()), Q_ARG(int, imuDivider_->currentData().toInt())); } }
void DeviceWindow::applySensorDetection(const QString& port, int baudRate, const QString& laserSerialNumber) { if (!port.isEmpty()) { const int index = imuPort_->findData(port); if (index >= 0) imuPort_->setCurrentIndex(index); const int baudIndex = imuBaud_->findData(baudRate); if (baudIndex >= 0) imuBaud_->setCurrentIndex(baudIndex); imuState_->setText(CRAWLING_TEXT("\xE8\x87\xAA""\xE5\x8A\xA8""\xE6\xA3\x80""\xE6\xB5\x8B""\xEF\xBC\x9A""%1 @ %2 bps").arg(port).arg(baudRate)); } if (!laserSerialNumber.isEmpty()) cameraState_->setText(CRAWLING_TEXT("\xE8\x87\xAA""\xE5\x8A\xA8""\xE6\xA3\x80""\xE6\xB5\x8B""\xE5\x88\xB0""\xE7\x9B\xB8""\xE6\x9C\xBA""\xEF\xBC\x9A""%1").arg(laserSerialNumber)); }
void DeviceWindow::scanCamera() { QMetaObject::invokeMethod(controller_, "scanCamera", Qt::QueuedConnection); }
void DeviceWindow::connectCamera() { if(cameraConnect_->text().startsWith(CRAWLING_TEXT("\xE6\x96\xAD""\xE5\xBC\x80"""))) QMetaObject::invokeMethod(controller_, "disconnectCamera", Qt::QueuedConnection); else QMetaObject::invokeMethod(controller_, "connectCamera", Qt::QueuedConnection, Q_ARG(QString, cameraList_->currentText())); }
void DeviceWindow::updateImu(const ImuSample& s) { imuValues_->setText(CRAWLING_TEXT("\xE5\xA7\xBF""\xE6\x80\x81"" (rad)\xEF\xBC\x9A""\xE6\xA8\xAA""\xE6\xBB\x9A"" %1\xEF\xBC\x8C""\xE4\xBF\xAF""\xE4\xBB\xB0"" %2\xEF\xBC\x8C""\xE8\x88\xAA""\xE5\x90\x91"" %3\n\xE9\x99\x80""\xE8\x9E\xBA""\xE4\xBB\xAA"" (rad/s)\xEF\xBC\x9A""X %4\xEF\xBC\x8C""Y %5\xEF\xBC\x8C""Z %6\n\xE5\x8A\xA0""\xE9\x80\x9F""\xE5\xBA\xA6"" (m/s2)\xEF\xBC\x9A""X %7\xEF\xBC\x8C""Y %8\xEF\xBC\x8C""Z %9").arg(s.rollRad,0,'f',3).arg(s.pitchRad,0,'f',3).arg(s.yawRad,0,'f',3).arg(s.gyroXRadps,0,'f',3).arg(s.gyroYRadps,0,'f',3).arg(s.gyroZRadps,0,'f',3).arg(s.accelerationXMps2,0,'f',3).arg(s.accelerationYMps2,0,'f',3).arg(s.accelerationZMps2,0,'f',3)); }
void DeviceWindow::updateImuState(bool c,const QString& m){ imuState_->setText(m); imuConnect_->setText(c?CRAWLING_TEXT("\xE6\x96\xAD""\xE5\xBC\x80"" IMU"):CRAWLING_TEXT("\xE8\xBF\x9E""\xE6\x8E\xA5"" IMU")); }
void DeviceWindow::updateDetectionState(bool running, const QString& message) { autoDetect_->setEnabled(!running); if (!message.isEmpty()) imuState_->setText(message); if (!running) refreshPorts(); }
void DeviceWindow::updateCameraList(const QStringList& d){ cameraList_->clear(); cameraList_->addItems(d); }
void DeviceWindow::updateCameraState(bool c,const QString& m){ cameraState_->setText(m); cameraConnect_->setText(c?CRAWLING_TEXT("\xE6\x96\xAD""\xE5\xBC\x80""\xE7\x9B\xB8""\xE6\x9C\xBA"""):CRAWLING_TEXT("\xE8\xBF\x9E""\xE6\x8E\xA5""\xE7\x9B\xB8""\xE6\x9C\xBA""")); }
void DeviceWindow::updateCameraFrame(quint32 f,quint32 w,quint32 h,quint64 p){ cameraFrame_->setText(CRAWLING_TEXT("帧 #%1，%2 x %3，三维点数 %4").arg(f).arg(w).arg(h).arg(p)); }
}  // namespace crawling
